### ISSUE TITLE
How to enable ssh logging

### ISSUE THREAD

**Issue by stephenboston** [rastasheep/ubuntu-sshd#12]
with release rastasheep/ubuntu-sshd five weeks ago (today is Jan19 2018) I am not seeing logs. 

What do I need to install/enable to get logging. 

=====

Update: 

# rsyslogd 

starts logging.

**Comment by stephenboston** [comment]
run #rsyslogd

**Comment by gipi** [comment]
I have the same problem and I solved it simply by adding the option ``-e`` to the ``sshd`` daemon.
