### ISSUE TITLE
default example command does not work

### ISSUE THREAD

**Issue by ghost** [rastasheep/ubuntu-sshd#23]
I ran the following on my local machine:
```
$ docker run -d -P --name test_sshd rastasheep/ubuntu-sshd:14.04`

$ docker port test_sshd 22
0.0.0.0:32769

$ ssh root@localhost -p 32769
Received disconnect from 127.0.0.1 port 32769:2: Too many authentication failures for root
Disconnected from 127.0.0.1 port 32769
```
My system is:

**Distributor ID:** Ubuntu
**Description:** Ubuntu 18.04 LTS
**Release:** 18.04
**Codename:** bionic

**Docker:** Docker version 18.03.1-ce, build 9ee9f40

I tried adding the `--privileged=true` flag with no luck.

**Comment by ghost** [comment]
Ignore that.  I was able to fix this by running:

`ssh root@localhost -p 32772 -o PreferredAuthentications=keyboard-interactive,password -o PubkeyAuthentication=no`

**Comment by rastasheep** [comment]
Awesome, no worries! It looks like in your case `ssh` wanted to authenticate via public key, and disabling that worked. Possible indicator for that would be to try ssh without options and enabled verbose debug.
