### ISSUE TITLE
connection refused on port 22

### ISSUE THREAD

**Issue by tarik-hatim** [rastasheep/ubuntu-sshd#26]
i built in image by using your Dockerfile  then i start the container ,but when i try to ssh into the container i get this error : 

$ ssh -v -v root@localhost
OpenSSH_7.6p1, OpenSSL 1.0.2l  25 May 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "localhost" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to localhost [::1] port 22.
debug1: connect to address ::1 port 22: Connection refused
debug1: Connecting to localhost [127.0.0.1] port 22.
debug1: connect to address 127.0.0.1 port 22: Connection refused
ssh: connect to host localhost port 22: Connection refused

**Comment by dagguh** [comment]
I got the same symptoms
