### ISSUE TITLE
About SCP file uploading

### ISSUE THREAD

**Issue by j-born** [rastasheep/ubuntu-sshd#7]
Hello

I can connect to container by ssh, but i can't upload file by scp
How I can do this?

**Comment by cmavr8** [comment]
My magic wand that allows me to read peoples' minds doesn't work tonight. You'll have to provide more info, including the exact error/response you're getting for anyone to help you. Please also increase scp verbosity, to get more meaningful error messages.

**Comment by rastasheep** [comment]
Scp should work just fine, as alternative aproach you can use doccker's [mount mechanism](http://stackoverflow.com/a/23455537/2760469).
